%%========================================================================================================================================================================
%%                  OUTPUT FOR UNBUFFERED ALOHA: ANALYSIS OF THROUGHPUT (S) AND TRANSMITTED LOAD (T) V/S OFFERED LOAD (G) 
%%========================================================================================================================================================================

N = 2;                      %% Number of nodes - needs to be parameterised in the future versions; Concretely ==> N = 2, 5, 10 and INF
T = 0.5;                    %% Initial value
dutyCycle = T/N;            %% Setting some value initially
d = 2;                      %% Packet duration
omega = 10;                 %% Packet generation rate 

S_unbuff_list = [];         %% Array to store the throuput info ====> useful info for later processing

%%================ ARRAYS USED FOR PLOTTING G VERSUS T ============================================================================================================

%%=========================================================================================================================================================================
%%                              FOR 2 ACTIVE NODES
%%=========================================================================================================================================================================
T_history_2 = [];
G_history_2 = [];

for G=0:10                                              %% G is the Offered Load
    
    T = G/(1 + G/N);                                    %% G = T / (1 - dutyCycle)
    G_history_2 = [G_history_2, G];                     %% Transmitted Load ======> Useful for plotting the graph between G and T
    T_history_2 = [T_history_2, T];
    collision1 = 1 - power((1 - dutyCycle), N - 1);     %% probability of type-1 collision
    
    P_t = exp(-omega * d);
    collision2 = 1 - power(P_t, N - 1);                 %% Throughoput for unbuffered ALOHA ===> S_unbuff
    
    S_unbuff_tmp = T*(1 - collision1)*(1 - collision2); %% Calculate this value for different values of the parameters and store it in an array
    S_unbuff_list = [S_unbuff_list, S_unbuff_tmp];      %% Appending the newest value, for plotting purposes
   
end

%%=========================================================================================================================================================================
%%                          FOR 5 ACTIVE NODES
%%=========================================================================================================================================================================
N = 5;
T_history_5 = [];
G_history_5 = [];

for G=0:10                                              %% G is the Offered Load
    
    T = G/(1 + G/N);                                    %% G = T / (1 - dutyCycle)
    G_history_5 = [G_history_5, G];
    T_history_5 = [T_history_5, T];

end
%%=========================================================================================================================================================================
%%                          FOR 10 ACTIVE NODES
%%=========================================================================================================================================================================
N = 10;
T_history_10 = [];
G_history_10 = [];

for G=0:10                                              %% G is the Offered Load
    
    T = G/(1 + G/N); 
    G_history_10 = [G_history_10, G];
    T_history_10 = [T_history_10, T];
    
end
%%=========================================================================================================================================================================
%%                          PLOTTING THE GRAPH
%%=========================================================================================================================================================================
plot(G_history_2, T_history_2, G_history_5, T_history_5, G_history_10, T_history_10);

title('Unbuffered ALOHA: Transmitted Load(T) versus Offered Load(G), N = No. of Active Nodes');
xlabel('Offered Load(G)')                               %% x-axis label; G = Average number of frames generated by the system during one frame transmission time (Unitless)
ylabel('Transmitted Load(T)')                           %% y-axis label; T = Transmitted Load

legend('N = 2', 'N  = 5', 'N = 10');
%%=========================================================================================================================================================================

